import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Preloader from "./Components/Preloader"; // import Preloader



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SOLSTRA INFO",
  description: "Generated by SOLSTRA INFO",
  icons: {
    icon: "/Logo.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Preloader logoSrc="/logo.jpg" companyName="  SOLSTRA INFO" duration={6000} />


        {children}
      </body>
    </html>
  );
}
