import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Preloader from "./Components/Preloader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "SOLSTRA INFO",
  description: "Generated by SOLSTRA INFO",
  icons: {
    icon: "/Logo.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className} antialiased`}>
        <Preloader logoSrc="/logo.jpg" companyName="SOLSTRA INFO" duration={6000} />
        {children}
      </body>
    </html>
  );
}
